package model.classic;

public class CityFr // extends Object // implicit
{
    private String codeInsee;
    private String name;
    private int population;

    // NB: following code is generated by the IDE

    public CityFr() {
    }

    public CityFr(String name) {
        this.name = name;
    }

    public CityFr(String codeInsee, String name, int population) {
        this.codeInsee = codeInsee;
        this.name = name;
        this.population = population;
    }

    public String getCodeInsee() {
        return codeInsee;
    }

    public void setCodeInsee(String codeInsee) {
        this.codeInsee = codeInsee;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPopulation() {
        return population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("CityFr{");
        sb.append("codeInsee='").append(codeInsee).append('\'');
        sb.append(", name='").append(name).append('\'');
        sb.append(", population=").append(population);
        sb.append('}');
        return sb.toString();
    }
}
